# Generated by Django 6.0.3 on 2026-03-11 15:58

from django.db import migrations, models


def consolidate_progress_singleton(apps, schema_editor):
    Progress = apps.get_model("journal", "Progress")
    rows = list(Progress.objects.order_by("pk"))
    if not rows:
        return

    singleton = next((row for row in rows if row.pk == 1), rows[0])
    singleton.total_xp = sum(row.total_xp for row in rows)
    singleton.level = max(1, (singleton.total_xp // 100) + 1)
    singleton.created_at = min(row.created_at for row in rows)
    singleton.updated_at = max(row.updated_at for row in rows)

    if singleton.pk != 1:
        singleton.pk = 1

    singleton.save()
    Progress.objects.exclude(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='cadence',
        ),
        migrations.RunPython(consolidate_progress_singleton, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.CheckConstraint(condition=models.Q(pk=1), name='progress_singleton_pk'),
        ),
    ]
