/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiQuestsRouteImport } from './routes/api/quests'
import { Route as ApiHabitsRouteImport } from './routes/api/habits'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiCheckInsTodayRouteImport } from './routes/api/check-ins/today'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiQuestsQuestIdCompleteRouteImport } from './routes/api/quests/$questId/complete'
import { Route as ApiHabitsHabitIdLogRouteImport } from './routes/api/habits/$habitId/log'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestsRoute = ApiQuestsRouteImport.update({
  id: '/api/quests',
  path: '/api/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHabitsRoute = ApiHabitsRouteImport.update({
  id: '/api/habits',
  path: '/api/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckInsTodayRoute = ApiCheckInsTodayRouteImport.update({
  id: '/api/check-ins/today',
  path: '/api/check-ins/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestsQuestIdCompleteRoute =
  ApiQuestsQuestIdCompleteRouteImport.update({
    id: '/$questId/complete',
    path: '/$questId/complete',
    getParentRoute: () => ApiQuestsRoute,
  } as any)
const ApiHabitsHabitIdLogRoute = ApiHabitsHabitIdLogRouteImport.update({
  id: '/$habitId/log',
  path: '/$habitId/log',
  getParentRoute: () => ApiHabitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/habits': typeof ApiHabitsRouteWithChildren
  '/api/quests': typeof ApiQuestsRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/check-ins/today': typeof ApiCheckInsTodayRoute
  '/api/habits/$habitId/log': typeof ApiHabitsHabitIdLogRoute
  '/api/quests/$questId/complete': typeof ApiQuestsQuestIdCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/habits': typeof ApiHabitsRouteWithChildren
  '/api/quests': typeof ApiQuestsRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/check-ins/today': typeof ApiCheckInsTodayRoute
  '/api/habits/$habitId/log': typeof ApiHabitsHabitIdLogRoute
  '/api/quests/$questId/complete': typeof ApiQuestsQuestIdCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/habits': typeof ApiHabitsRouteWithChildren
  '/api/quests': typeof ApiQuestsRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/check-ins/today': typeof ApiCheckInsTodayRoute
  '/api/habits/$habitId/log': typeof ApiHabitsHabitIdLogRoute
  '/api/quests/$questId/complete': typeof ApiQuestsQuestIdCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/dashboard'
    | '/api/habits'
    | '/api/quests'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/check-ins/today'
    | '/api/habits/$habitId/log'
    | '/api/quests/$questId/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/dashboard'
    | '/api/habits'
    | '/api/quests'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/check-ins/today'
    | '/api/habits/$habitId/log'
    | '/api/quests/$questId/complete'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/dashboard'
    | '/api/habits'
    | '/api/quests'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/check-ins/today'
    | '/api/habits/$habitId/log'
    | '/api/quests/$questId/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiHabitsRoute: typeof ApiHabitsRouteWithChildren
  ApiQuestsRoute: typeof ApiQuestsRouteWithChildren
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCheckInsTodayRoute: typeof ApiCheckInsTodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quests': {
      id: '/api/quests'
      path: '/api/quests'
      fullPath: '/api/quests'
      preLoaderRoute: typeof ApiQuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/habits': {
      id: '/api/habits'
      path: '/api/habits'
      fullPath: '/api/habits'
      preLoaderRoute: typeof ApiHabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-ins/today': {
      id: '/api/check-ins/today'
      path: '/api/check-ins/today'
      fullPath: '/api/check-ins/today'
      preLoaderRoute: typeof ApiCheckInsTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quests/$questId/complete': {
      id: '/api/quests/$questId/complete'
      path: '/$questId/complete'
      fullPath: '/api/quests/$questId/complete'
      preLoaderRoute: typeof ApiQuestsQuestIdCompleteRouteImport
      parentRoute: typeof ApiQuestsRoute
    }
    '/api/habits/$habitId/log': {
      id: '/api/habits/$habitId/log'
      path: '/$habitId/log'
      fullPath: '/api/habits/$habitId/log'
      preLoaderRoute: typeof ApiHabitsHabitIdLogRouteImport
      parentRoute: typeof ApiHabitsRoute
    }
  }
}

interface ApiHabitsRouteChildren {
  ApiHabitsHabitIdLogRoute: typeof ApiHabitsHabitIdLogRoute
}

const ApiHabitsRouteChildren: ApiHabitsRouteChildren = {
  ApiHabitsHabitIdLogRoute: ApiHabitsHabitIdLogRoute,
}

const ApiHabitsRouteWithChildren = ApiHabitsRoute._addFileChildren(
  ApiHabitsRouteChildren,
)

interface ApiQuestsRouteChildren {
  ApiQuestsQuestIdCompleteRoute: typeof ApiQuestsQuestIdCompleteRoute
}

const ApiQuestsRouteChildren: ApiQuestsRouteChildren = {
  ApiQuestsQuestIdCompleteRoute: ApiQuestsQuestIdCompleteRoute,
}

const ApiQuestsRouteWithChildren = ApiQuestsRoute._addFileChildren(
  ApiQuestsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiHabitsRoute: ApiHabitsRouteWithChildren,
  ApiQuestsRoute: ApiQuestsRouteWithChildren,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCheckInsTodayRoute: ApiCheckInsTodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
